In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats


In [52]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [4]:
df = pd.read_csv('dataset.csv')

In [5]:
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [6]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [7]:
df.describe()

SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [8]:
df['gender'].unique()

array(['Female', 'Male'], dtype=object)

In [9]:
df['gender'].value_counts()

Male      3555
Female    3488
Name: gender, dtype: int64

In [10]:
df['SeniorCitizen'].unique()

array([0, 1], dtype=int64)

In [11]:
df['SeniorCitizen'].value_counts()

0    5901
1    1142
Name: SeniorCitizen, dtype: int64

In [12]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [13]:
gender_column = df['gender']
ngender = pd.get_dummies(gender_column,columns=['gender'])

In [14]:
ngender.head()

Female  Male
0       1     0
1       0     1
2       0     1
3       0     1
4       1     0

In [15]:
df=pd.concat([df,ngender],axis=1)

In [16]:
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... StreamingTV  \
0  No phone service             DSL             No  ...          No   
1                No             DSL            Yes  ...          No   
2                No             DSL            Yes  ...          No   
3  No phone service             DSL            Yes  ...          No   
4                No     Fiber optic             No  ...          No   

  StreamingMovies        Contract PaperlessBilling              PaymentMethod  \
0              No  Month-to-month              Yes           Electronic check   
1              No        One year               No               Mailed check   
2              No  Month-to-month              Yes               Mailed check   
3              No        One year               No  Bank transfer (automatic)   
4              No  Month-to-month              Yes           Electronic check   

  MonthlyCharges TotalCharges Churn  Female Male  
0          29.85        29.85    No       1    0  
1          56.95       1889.5    No       0    1  
2          53.85       108.15   Yes       0    1  
3          42.30      1840.75    No       0    1  
4          70.70       151.65   Yes       1    0  

[5 rows x 23 columns]

In [17]:
df.drop('gender',axis=1,inplace=True)

In [18]:
df.head()

customerID  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG              0     Yes         No       1           No   
1  5575-GNVDE              0      No         No      34          Yes   
2  3668-QPYBK              0      No         No       2          Yes   
3  7795-CFOCW              0      No         No      45           No   
4  9237-HQITU              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity OnlineBackup  ...  \
0  No phone service             DSL             No          Yes  ...   
1                No             DSL            Yes           No  ...   
2                No             DSL            Yes          Yes  ...   
3  No phone service             DSL            Yes           No  ...   
4                No     Fiber optic             No           No  ...   

  StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No              No  Month-to-month              Yes   
1          No              No        One year               No   
2          No              No  Month-to-month              Yes   
3          No              No        One year               No   
4          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges TotalCharges  Churn Female Male  
0           Electronic check          29.85        29.85     No      1    0  
1               Mailed check          56.95       1889.5     No      0    1  
2               Mailed check          53.85       108.15    Yes      0    1  
3  Bank transfer (automatic)          42.30      1840.75     No      0    1  
4           Electronic check          70.70       151.65    Yes      1    0  

[5 rows x 22 columns]

In [19]:
dataonehot = df[['Partner','PhoneService','InternetService','Contract','PaymentMethod','Churn']]
dataonehot.head()

Partner PhoneService InternetService        Contract  \
0     Yes           No             DSL  Month-to-month   
1      No          Yes             DSL        One year   
2      No          Yes             DSL  Month-to-month   
3      No           No             DSL        One year   
4      No          Yes     Fiber optic  Month-to-month   

               PaymentMethod Churn  
0           Electronic check    No  
1               Mailed check    No  
2               Mailed check   Yes  
3  Bank transfer (automatic)    No  
4           Electronic check   Yes

In [20]:
ndataonehot = pd.get_dummies(dataonehot,columns=['Partner','PhoneService','InternetService','Contract','PaymentMethod','Churn'])
df.drop(['Partner','PhoneService','InternetService','Contract','PaymentMethod','Churn'],axis=1,inplace=True)
df=pd.concat([df,ndataonehot],axis=1)


In [21]:
df.head()

customerID  SeniorCitizen Dependents  tenure     MultipleLines  \
0  7590-VHVEG              0         No       1  No phone service   
1  5575-GNVDE              0         No      34                No   
2  3668-QPYBK              0         No       2                No   
3  7795-CFOCW              0         No      45  No phone service   
4  9237-HQITU              0         No       2                No   

  OnlineSecurity OnlineBackup DeviceProtection TechSupport StreamingTV  ...  \
0             No          Yes               No          No          No  ...   
1            Yes           No              Yes          No          No  ...   
2            Yes          Yes               No          No          No  ...   
3            Yes           No              Yes         Yes          No  ...   
4             No           No               No          No          No  ...   

  InternetService_No Contract_Month-to-month  Contract_One year  \
0                  0                       1                  0   
1                  0                       0                  1   
2                  0                       1                  0   
3                  0                       0                  1   
4                  0                       1                  0   

  Contract_Two year  PaymentMethod_Bank transfer (automatic)  \
0                 0                                        0   
1                 0                                        0   
2                 0                                        0   
3                 0                                        1   
4                 0                                        0   

   PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
0                                      0                               1   
1                                      0                               0   
2                                      0                               0   
3                                      0                               0   
4                                      0                               1   

   PaymentMethod_Mailed check  Churn_No  Churn_Yes  
0                           0         1          0  
1                           1         1          0  
2                           1         0          1  
3                           0         1          0  
4                           0         0          1  

[5 rows x 32 columns]

In [22]:
df.drop(['Dependents','MultipleLines','OnlineSecurity','OnlineBackup','DeviceProtection','TechSupport','StreamingTV'],axis=1,inplace=True)

In [23]:
df.head()

customerID  SeniorCitizen  tenure StreamingMovies PaperlessBilling  \
0  7590-VHVEG              0       1              No              Yes   
1  5575-GNVDE              0      34              No               No   
2  3668-QPYBK              0       2              No              Yes   
3  7795-CFOCW              0      45              No               No   
4  9237-HQITU              0       2              No              Yes   

   MonthlyCharges TotalCharges  Female  Male  Partner_No  ...  \
0           29.85        29.85       1     0           0  ...   
1           56.95       1889.5       0     1           1  ...   
2           53.85       108.15       0     1           1  ...   
3           42.30      1840.75       0     1           1  ...   
4           70.70       151.65       1     0           1  ...   

   InternetService_No  Contract_Month-to-month  Contract_One year  \
0                   0                        1                  0   
1                   0                        0                  1   
2                   0                        1                  0   
3                   0                        0                  1   
4                   0                        1                  0   

   Contract_Two year  PaymentMethod_Bank transfer (automatic)  \
0                  0                                        0   
1                  0                                        0   
2                  0                                        0   
3                  0                                        1   
4                  0                                        0   

   PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
0                                      0                               1   
1                                      0                               0   
2                                      0                               0   
3                                      0                               0   
4                                      0                               1   

   PaymentMethod_Mailed check  Churn_No  Churn_Yes  
0                           0         1          0  
1                           1         1          0  
2                           1         0          1  
3                           0         1          0  
4                           0         0          1  

[5 rows x 25 columns]

In [24]:
df.drop(['PaperlessBilling'],axis=1,inplace=True)

In [25]:
df.drop(['StreamingMovies'],axis=1,inplace=True)

In [26]:
df.head()

customerID  SeniorCitizen  tenure  MonthlyCharges TotalCharges  Female  \
0  7590-VHVEG              0       1           29.85        29.85       1   
1  5575-GNVDE              0      34           56.95       1889.5       0   
2  3668-QPYBK              0       2           53.85       108.15       0   
3  7795-CFOCW              0      45           42.30      1840.75       0   
4  9237-HQITU              0       2           70.70       151.65       1   

   Male  Partner_No  Partner_Yes  PhoneService_No  ...  InternetService_No  \
0     0           0            1                1  ...                   0   
1     1           1            0                0  ...                   0   
2     1           1            0                0  ...                   0   
3     1           1            0                1  ...                   0   
4     0           1            0                0  ...                   0   

   Contract_Month-to-month  Contract_One year  Contract_Two year  \
0                        1                  0                  0   
1                        0                  1                  0   
2                        1                  0                  0   
3                        0                  1                  0   
4                        1                  0                  0   

   PaymentMethod_Bank transfer (automatic)  \
0                                        0   
1                                        0   
2                                        0   
3                                        1   
4                                        0   

   PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
0                                      0                               1   
1                                      0                               0   
2                                      0                               0   
3                                      0                               0   
4                                      0                               1   

   PaymentMethod_Mailed check  Churn_No  Churn_Yes  
0                           0         1          0  
1                           1         1          0  
2                           1         0          1  
3                           0         1          0  
4                           0         0          1  

[5 rows x 23 columns]

In [27]:
df.drop('customerID',axis=1,inplace=True)
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df.dropna(inplace=True)


In [28]:
df.head()
ndf = df.copy()

In [29]:
ndf.drop('Churn_No',axis=1,inplace=True)

In [30]:
y = ndf['Churn_Yes']

In [31]:
ndf.drop(['Churn_Yes'],axis=1,inplace=True)
X = ndf

In [32]:
y.head()

0    0
1    0
2    1
3    0
4    1
Name: Churn_Yes, dtype: uint8

In [33]:
X.head()

SeniorCitizen  tenure  MonthlyCharges  TotalCharges  Female  Male  \
0              0       1           29.85         29.85       1     0   
1              0      34           56.95       1889.50       0     1   
2              0       2           53.85        108.15       0     1   
3              0      45           42.30       1840.75       0     1   
4              0       2           70.70        151.65       1     0   

   Partner_No  Partner_Yes  PhoneService_No  PhoneService_Yes  \
0           0            1                1                 0   
1           1            0                0                 1   
2           1            0                0                 1   
3           1            0                1                 0   
4           1            0                0                 1   

   InternetService_DSL  InternetService_Fiber optic  InternetService_No  \
0                    1                            0                   0   
1                    1                            0                   0   
2                    1                            0                   0   
3                    1                            0                   0   
4                    0                            1                   0   

   Contract_Month-to-month  Contract_One year  Contract_Two year  \
0                        1                  0                  0   
1                        0                  1                  0   
2                        1                  0                  0   
3                        0                  1                  0   
4                        1                  0                  0   

   PaymentMethod_Bank transfer (automatic)  \
0                                        0   
1                                        0   
2                                        0   
3                                        1   
4                                        0   

   PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
0                                      0                               1   
1                                      0                               0   
2                                      0                               0   
3                                      0                               0   
4                                      0                               1   

   PaymentMethod_Mailed check  
0                           0  
1                           1  
2                           1  
3                           0  
4                           0

In [34]:
del ndf

In [35]:
def test_train(X,y,test_size=0.2,random_state=42):
    return train_test_split(X,y,test_size=test_size,random_state=random_state)


In [36]:
X_train, X_test, y_train, y_test = test_train(X,y)

In [37]:
X_train.head()

SeniorCitizen  tenure  MonthlyCharges  TotalCharges  Female  Male  \
6030              0      43           49.05       2076.20       1     0   
3410              0       3           53.40        188.70       0     1   
5483              0      55           77.75       4458.15       1     0   
5524              0      45           54.65       2553.70       0     1   
6337              0      55          100.90       5448.60       1     0   

      Partner_No  Partner_Yes  PhoneService_No  PhoneService_Yes  \
6030           1            0                1                 0   
3410           1            0                0                 1   
5483           0            1                0                 1   
5524           0            1                0                 1   
6337           0            1                0                 1   

      InternetService_DSL  InternetService_Fiber optic  InternetService_No  \
6030                    1                            0                   0   
3410                    1                            0                   0   
5483                    0                            1                   0   
5524                    1                            0                   0   
6337                    0                            1                   0   

      Contract_Month-to-month  Contract_One year  Contract_Two year  \
6030                        1                  0                  0   
3410                        1                  0                  0   
5483                        1                  0                  0   
5524                        0                  0                  1   
6337                        0                  1                  0   

      PaymentMethod_Bank transfer (automatic)  \
6030                                        1   
3410                                        0   
5483                                        0   
5524                                        1   
6337                                        0   

      PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
6030                                      0                               0   
3410                                      1                               0   
5483                                      0                               1   
5524                                      0                               0   
6337                                      0                               0   

      PaymentMethod_Mailed check  
6030                           0  
3410                           0  
5483                           0  
5524                           0  
6337                           1

In [38]:
def logisticRegression(X_train,y_train,X_test,y_test):
    pipeline = Pipeline([
        ('scalar',StandardScaler()),
        ('classifier',LogisticRegression())
    ])
    pipeline.fit(X_train,y_train)
    y_pred = pipeline.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    class_report = classification_report(y_test, y_pred)
    
    print("Accuracy:", accuracy)
    print("Confusion Matrix:\n", conf_matrix)
    print("Classification Report:\n", class_report)
    
    return pipeline
    



In [39]:
model = logisticRegression(X_train,y_train,X_test,y_test)

Accuracy: 0.7818052594171997
Confusion Matrix:
 [[915 118]
 [189 185]]
Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.89      0.86      1033
           1       0.61      0.49      0.55       374

    accuracy                           0.78      1407
   macro avg       0.72      0.69      0.70      1407
weighted avg       0.77      0.78      0.77      1407



In [40]:
def KNN(X_train,y_train,X_test,y_test):
    
    pipeline = Pipeline([
        ('scalar',StandardScaler()),
        ('classifier',KNeighborsClassifier())
        
    ])
    pipeline.fit(X_train,y_train)
    y_pred = pipeline.predict(X_test)
    accuracy = accuracy_score(y_test,y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    class_report = classification_report(y_test, y_pred)
    
    print("Accuracy:", accuracy)
    print("Confusion Matrix:\n", conf_matrix)
    print("Classification Report:\n", class_report)
    
    return pipeline
    

In [41]:
model = KNN(X_train,y_train,X_test,y_test)

Accuracy: 0.7448471926083866
Confusion Matrix:
 [[875 158]
 [201 173]]
Classification Report:
               precision    recall  f1-score   support

           0       0.81      0.85      0.83      1033
           1       0.52      0.46      0.49       374

    accuracy                           0.74      1407
   macro avg       0.67      0.65      0.66      1407
weighted avg       0.74      0.74      0.74      1407



In [42]:
def dtClassifier(X_train,y_train,X_test,y_test):
    
    pipeline = Pipeline([
        ('scalar',StandardScaler()),
        ('classifier',DecisionTreeClassifier())
        
    ])
    pipeline.fit(X_train,y_train)
    y_pred = pipeline.predict(X_test)
    accuracy = accuracy_score(y_test,y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    class_report = classification_report(y_test, y_pred)
    
    print("Accuracy:", accuracy)
    print("Confusion Matrix:\n", conf_matrix)
    print("Classification Report:\n", class_report)
    
    return pipeline
    

In [43]:
model = dtClassifier(X_train,y_train,X_test,y_test)

Accuracy: 0.7192608386638237
Confusion Matrix:
 [[830 203]
 [192 182]]
Classification Report:
               precision    recall  f1-score   support

           0       0.81      0.80      0.81      1033
           1       0.47      0.49      0.48       374

    accuracy                           0.72      1407
   macro avg       0.64      0.65      0.64      1407
weighted avg       0.72      0.72      0.72      1407



In [44]:
def randomForestClassifier(X_train,y_train,X_test,y_test):
    
    pipeline = Pipeline([
        ('scalar',StandardScaler()),
        ('classifier',RandomForestClassifier())
        
    ])
    pipeline.fit(X_train,y_train)
    y_pred = pipeline.predict(X_test)
    accuracy = accuracy_score(y_test,y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    class_report = classification_report(y_test, y_pred)
    
    print("Accuracy:", accuracy)
    print("Confusion Matrix:\n", conf_matrix)
    print("Classification Report:\n", class_report)
    
    return pipeline
    

In [45]:
model = randomForestClassifier(X_train,y_train,X_test,y_test)

Accuracy: 0.7526652452025586
Confusion Matrix:
 [[888 145]
 [203 171]]
Classification Report:
               precision    recall  f1-score   support

           0       0.81      0.86      0.84      1033
           1       0.54      0.46      0.50       374

    accuracy                           0.75      1407
   macro avg       0.68      0.66      0.67      1407
weighted avg       0.74      0.75      0.75      1407



SeniorCitizen  tenure  MonthlyCharges  TotalCharges  Female  Male  \
0                 0       1           29.85         29.85       1     0   
1                 0      34           56.95       1889.50       0     1   
2                 0       2           53.85        108.15       0     1   
3                 0      45           42.30       1840.75       0     1   
4                 0       2           70.70        151.65       1     0   
...             ...     ...             ...           ...     ...   ...   
7038              0      24           84.80       1990.50       0     1   
7039              0      72          103.20       7362.90       1     0   
7040              0      11           29.60        346.45       1     0   
7041              1       4           74.40        306.60       0     1   
7042              0      66          105.65       6844.50       0     1   

      Partner_No  Partner_Yes  PhoneService_No  PhoneService_Yes  ...  \
0              0            1                1                 0  ...   
1              1            0                0                 1  ...   
2              1            0                0                 1  ...   
3              1            0                1                 0  ...   
4              1            0                0                 1  ...   
...          ...          ...              ...               ...  ...   
7038           0            1                0                 1  ...   
7039           0            1                0                 1  ...   
7040           0            1                1                 0  ...   
7041           0            1                0                 1  ...   
7042           1            0                0                 1  ...   

      InternetService_No  Contract_Month-to-month  Contract_One year  \
0                      0                        1                  0   
1                      0                        0                  1   
2                      0                        1                  0   
3                      0                        0                  1   
4                      0                        1                  0   
...                  ...                      ...                ...   
7038                   0                        0                  1   
7039                   0                        0                  1   
7040                   0                        1                  0   
7041                   0                        1                  0   
7042                   0                        0                  0   

      Contract_Two year  PaymentMethod_Bank transfer (automatic)  \
0                     0                                        0   
1                     0                                        0   
2                     0                                        0   
3                     0                                        1   
4                     0                                        0   
...                 ...                                      ...   
7038                  0                                        0   
7039                  0                                        0   
7040                  0                                        0   
7041                  0                                        0   
7042                  1                                        1   

      PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check  \
0                                         0                               1   
1                                         0                               0   
2                                         0                               0   
3                                         0                               0   
4                                         0                               1   
...                                     ...                             

In [54]:
pipeline = logisticRegression(X_train,y_train,X_test,y_test)

Accuracy: 0.7818052594171997
Confusion Matrix:
 [[915 118]
 [189 185]]
Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.89      0.86      1033
           1       0.61      0.49      0.55       374

    accuracy                           0.78      1407
   macro avg       0.72      0.69      0.70      1407
weighted avg       0.77      0.78      0.77      1407



In [62]:
param_grid = {'classifier__C': np.logspace(-1, 10, 100)} 
grid_search = GridSearchCV(pipeline, param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)
best_C = grid_search.best_params_['classifier__C']
print(f'Best C: {best_C}')

Best C: 0.5994842503189409


In [63]:
pipeline = Pipeline([
        ('scalar',StandardScaler()),
        ('classifier',LogisticRegression(C=best_C, solver='liblinear'))
    ])
pipeline.fit(X_train,y_train)
y_pred = pipeline.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

Accuracy: 0.7818052594171997
Confusion Matrix:
 [[915 118]
 [189 185]]
Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.89      0.86      1033
           1       0.61      0.49      0.55       374

    accuracy                           0.78      1407
   macro avg       0.72      0.69      0.70      1407
weighted avg       0.77      0.78      0.77      1407

